### ISSUE TITLE
Omit jdk7 in kotlin-stdlib dependency definition (Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules)

### ISSUE THREAD

**Issue by drahoslove** [customerly/Customerly-ReactNative-SDK#13]
One small thing.

According to this doc https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target,
since you upgraded your kotlinVersion to 1.8.0, you should update the kotlin-stdib dependency in the `build.gradle` file followingly:

```diff
@@ -42,6 +42,6 @@ dependencies {
     implementation 'com.facebook.react:react-native:+'
     api 'io.customerly:customerly-android-sdk:3.1.3'
     implementation 'org.jetbrains:annotations:24.1.0'
-    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"
+    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
 }
   
```

We faced some dependency resolution issues when building the app for android (`Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules ...`) - not sure whether it was something specific to our setup, but patching that line in your `build.gradle` fixed it for us.

**Comment by GiorgioBertolotti** [comment]
@drahoslove thanks for reporting, just tried it and everything seems to work fine, great job 👍🏼
