### ISSUE TITLE
Value for SWIFT_VERSION cannot be empty

### ISSUE THREAD

**Issue by tommypd** [customerly/Customerly-ReactNative-SDK#3]
Hi!
Im not able to include Customerly’s SDK in a react Native Application. I followed the steps of this guide: https://github.com/customerly/Customerly-ReactNative-SDK
<img width="1265" alt="schermata 2018-12-28 alle 22 35 34" src="https://user-images.githubusercontent.com/13138114/50540075-90d8d580-0b8b-11e9-8ad9-828fc37f1bd6.png">
, it works properly on Android. Besides when I try to build on Xcode 10.1 I receive this error: "Value for SWIFT_VERSION cannot be empty"
Someone can help me? 
Thanks

**Comment by pmusolino** [comment]
Hi there. What version of Swift are you using in your project?

**Comment by tommypd** [comment]
> Hi there. What version of Swift are you using in your project?

Hi , Version 10.1 (10B61)

**Comment by pmusolino** [comment]
I mean Swift, not Xcode 👍

**Comment by tommypd** [comment]
> I mean Swift, not Xcode 👍

I don’t know the Swift Versione, I can’t find the option on Xcode 10, you know where I can find it?

**Comment by pmusolino** [comment]
1) Select your app target
2) Select build settings
3) Search "swift language version"

**Comment by tommypd** [comment]
> 1. Select your app target
> 2. Select build settings
> 3. Search "swift language version"

is not on xcode 10, anyway find it with Terminal :
 
swift --version
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.2.0

**Comment by harrycamelback** [comment]
Hi @tommypd, if you try our latest version, you can see that the problem was fixed.
