### ISSUE TITLE
Android building issue with kotlin and annotation

### ISSUE THREAD

**Issue by monossido** [customerly/Customerly-ReactNative-SDK#4]
Recently I've upgraded my project from RN 0.56 to RN 0.61 (a nightmare) and customerly started to have this android building errors:

> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:18: error: package org.jetbrains.annotations does not exist
> import org.jetbrains.annotations.Contract;
>                                 ^
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:25: error: package kotlin does not exist
> import kotlin.Unit;
>              ^
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:26: error: package kotlin.jvm.functions does not exist
> import kotlin.jvm.functions.Function0;
>                            ^
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:327: error: cannot find symbol
>     @Contract("null -> null; !null->!null")
>      ^
>   symbol:   class Contract
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:365: error: cannot find symbol
>     @Contract("null -> null; !null->!null")
>      ^
>   symbol:   class Contract
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:71: error: cannot find symbol
>                 new Function0<Unit>() {
>                     ^
>   symbol:   class Function0
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:71: error: cannot find symbol
>                 new Function0<Unit>() {
>                               ^
>   symbol:   class Unit
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:78: error: cannot find symbol
>                 new Function0<Unit>() {
>                     ^
>   symbol:   class Function0
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:78: error: cannot find symbol
>                 new Function0<Unit>() {
>                               ^
>   symbol:   class Unit
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:164: error: cannot find symbol
>                 new Function0<Unit>() {
>                     ^
>   symbol:   class Function0
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:164: error: cannot find symbol
>                 new Function0<Unit>() {
>                               ^
>   symbol:   class Unit
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:173: error: cannot find symbol
>                 new Function0<Unit>() {
>                     ^
>   symbol:   class Function0
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:173: error: cannot find symbol
>                 new Function0<Unit>() {
>                               ^
>   symbol:   class Unit
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:162: error: cannot access Pair
>         Customerly.setAttributes(
>                   ^
>   class file for kotlin.Pair not found
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:197: error: cannot find symbol
>                 new Function0<Unit>() {
>                     ^
>   symbol:   class Function0
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:197: error: cannot find symbol
>                 new Function0<Unit>() {
>                               ^
>   symbol:   class Unit
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:206: error: cannot find symbol
>                 new Function0<Unit>() {
>                     ^
>   symbol:   class Function0
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:206: error: cannot find symbol
>                 new Function0<Unit>() {
>                               ^
>   symbol:   class Unit
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:282: error: cannot find symbol
>                 new Function0<Unit>() {
>                     ^
>   symbol:   class Function0
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:282: error: cannot find symbol
>                 new Function0<Unit>() {
>                               ^
>   symbol:   class Unit
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:291: error: cannot find symbol
>                 new Function0<Unit>() {
>                     ^
>   symbol:   class Function0
>   location: class RNCustomerlyModule
> unipiazza/node_modules/react-native-customerly/android/src/main/java/io/customerly/rn/RNCustomerlyModule.java:291: error: cannot find symbol
>                 new Function0<Unit>() {
>                               ^
>   symbol:   class Unit
>   location: class RNCustomerlyModule
> 22 errors
> 

fixed inserting this two lines in node_modules/react-native-customerly/android/build.gradle

```
implementation 'org.jetbrains:annotations:16.0.2'
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
```

**Comment by giannign1** [comment]
Great!
Please try the last update that should include the missing libraries
