### ISSUE TITLE
Podspec error

### ISSUE THREAD

**Issue by tommypd** [customerly/Customerly-ReactNative-SDK#5]
Upgrading from RN 0.56 to 0.61 on ios I have this error

> The `RNCustomerly` pod failed to validate due to 1 error:
>     - ERROR | attributes: Missing required attribute `homepage`.

Fixed adding 

>   s.homepage     = "https://github.com/customerly/Customerly-ReactNative-SDK"

in
node_modules/react-native-customerly/RNCustomerly.podspec

**Comment by harrycamelback** [comment]
This problem was fixed in our latest version 👍
