### ISSUE TITLE
'CustomerlySDK/CustomerlySDK-Swift.h' file not found

### ISSUE THREAD

**Issue by david-gregorian** [customerly/Customerly-ReactNative-SDK#6]
Hi there,
Apparently I get this error when trying to run the project. Also tried via xCode directly.

RN Version: 0.61.5

Thanks in advance!

**Comment by harrycamelback** [comment]
I there. Did you follow the entire procedure from the readme? This happens when you miss one of the steps.

**Comment by david-gregorian** [comment]
Hi @harrycamelback, yes I followed every step from the readme even :)

**Comment by harrycamelback** [comment]
Did you run `pod install` in your `ios` folder? Are you able to see the `react-native-customerly` folder under `node_modules`?

**Comment by david-gregorian** [comment]
@harrycamelback yes I did that and i can see the installed node modules folder. I can also see the pod import path in the pod file

**Comment by harrycamelback** [comment]
Do you ever integrated a Swift library in your project? If the answer is no, try to open your xcode project, add a swift file, and make sure the bridging header was generated. Then cancel the swift file you added, and try to rerun the project.

**Comment by david-gregorian** [comment]
I did never add a swift library. So i tried what you said. Created the Bride file and deleted the newly created swift file. Afterwards i went through the README process again.
Same error :/

**Comment by harrycamelback** [comment]
Can you try a clean (from xcode) and try to remove derived data?
It's a really generic error

**Comment by david-gregorian** [comment]
@harrycamelback tried that as well. Still same issue.
Do I need to add something specific into the bride file for swift -> objective-c ?

**Comment by vssalcedo** [comment]
Hi @daveGregorian, any updates on this? Did you get this working?

**Comment by alon7** [comment]
Same issue here:
```
AppDelegate.m:18:9: 'CustomerlySDK/CustomerlySDK-Swift.h' file not found
```

**Comment by harrycamelback** [comment]
Please, contact our customer support, we can help you all solving this issue.

**Comment by GD55** [comment]
getting same issue any pointers??

**Comment by Reizar** [comment]
For anyone who is interested, I found the solution to this problem ( at least, this is a solution that worked for me ).
( I had also done the above suggested tips and added an empty Swift file )

The Customerly iOS pod needs to be built with `use_frameworks!` in the Podfile. ( Found this from looking at the iOS library ). 
However this will most likely cause issues depending on what React Native libraries you have installed. 

Adding this code to your Podfile inside the main app target should mitigate those issues
```ruby
# ios/Podfile
target 'AppName' do
  config = use_native_modules!
  use_frameworks!
  use_react_native!(:path => config["reactNativePath"])

  ...
  dynamic_frameworks = ['CustomerlySDK' ]
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if !dynamic_frameworks.include?(pod.name)
        puts "Overriding the static_framework? method for #{pod.name}"
        def pod.static_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
...
end
```

This will essentially set the default to be to use frameworks for all pods, but skip it for any pod that isn't CustomerlySDK.

Notes:
- Make sure to clean build folder / derived data.
- If you get any errors when running `pod install` about transient libraries, Add those libraries names to the dynamic_frameworks array.
- Make sure to remove the `...`'s I have above in the Podfile if you cope paste, its just there to indicate your code that might already exist.
- You will need to change the code in AppDelegate.m to this: `[[Customerly sharedInstance] configureWithAppId:@"APP ID" widgetColor:NULL];`

Hope this helps anyone having issues.
