### ISSUE TITLE
package android.support.annotation does not exist

### ISSUE THREAD

**Issue by gevorgsahakyann** [customerly/Customerly-ReactNative-SDK#7]
Hi there. I get this error when trying to run the project.

I guess imports should be changed to `import androidx.annotation.NonNull;`...

RN Version: 0.62.2

<img width="688" alt="Screen Shot 2020-06-20 at 10 27 20" src="https://user-images.githubusercontent.com/45065751/85195116-e4d7fc80-b2e0-11ea-8861-ea7a125909c4.png">

**Comment by giannign1** [comment]
Sure they should... i'll fix it asap
Thank you for notice it

**Comment by gevorgsahakyann** [comment]
Thanks for the quick response)

**Comment by giannign1** [comment]
You can find the new release here
https://github.com/Customerly/Customerly-ReactNative-SDK/releases/tag/1.1.7
